name: id-pos-tagging
channels:
- conda-forge
- defaults
- pytorch
dependencies:
- python-crfsuite=0.9.2
- dill=0.2.7.1
- flake8=3.5.0
- nltk=3.2.5
- numpy=1.14.2
- pandas=0.22.0
- pymongo=3.4.0
- python=3.6.5
- seaborn=0.8.1
- scikit-learn=0.19.1
- scipy=1.0.1
- spacy=2.0.10
- pytorch=0.3.1
- pip:
    - camel==0.1.2
    - flake8-mypy==17.8.0
    - pytorch-crf==0.5.1
    - sacred==0.7.3
    - torchtext==0.2.3
    - git+https://github.com/pytorch/tnt.git@464aa4#egg=torchnet
